In [276]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as mlt
import seaborn as sb

In [277]:
df = pd.read_csv("C:\GEN1_AI\Dataset\Machine_Learning\Weather\city_day.csv")

<>:1: SyntaxWarning:

invalid escape sequence '\G'

<>:1: SyntaxWarning:

invalid escape sequence '\G'

C:\Users\Anooj Dilip Archana\AppData\Local\Temp\ipykernel_36848\4067115021.py:1: SyntaxWarning:

invalid escape sequence '\G'

In [278]:
df

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.02,50.94,7.68,25.06,19.54,12.47,0.47,8.55,23.30,2.24,12.07,0.73,41.0,Good
29527,Visakhapatnam,2020-06-28,24.38,74.09,3.42,26.06,16.53,11.99,0.52,12.72,30.14,0.74,2.21,0.38,70.0,Satisfactory
29528,Visakhapatnam,2020-06-29,22.91,65.73,3.45,29.53,18.33,10.71,0.48,8.42,30.96,0.01,0.01,0.00,68.0,Satisfactory
29529,Visakhapatnam,2020-06-30,16.64,49.97,4.05,29.26,18.80,10.03,0.52,9.84,28.30,0.00,0.00,0.00,54.0,Satisfactory
29530,Visakhapatnam,2020-07-01,15.00,66.00,0.40,26.85,14.05,5.20,0.59,2.10,17.05,NaN,NaN,NaN,50.0,Good

In [279]:
df.shape

(29531, 16)

In [280]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  object
 1   Date        29531 non-null  object
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  object
dtypes: float64(13), object(3)
memory usage: 3.6+ MB

In [281]:
df.isnull().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [282]:
df.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [283]:
df.columns

Index(['City', 'Date', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2',
       'O3', 'Benzene', 'Toluene', 'Xylene', 'AQI', 'AQI_Bucket'],
      dtype='object')

In [284]:
df2 = df.copy()

In [285]:
df2 = df2.fillna(df2.mean(numeric_only=True))

In [286]:
df2

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,67.450578,118.127103,0.92,18.22,17.15,23.483476,0.92,27.64,133.36,0.00000,0.020000,0.000000,166.463581,NaN
1,Ahmedabad,2015-01-02,67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68000,5.500000,3.770000,166.463581,NaN
2,Ahmedabad,2015-01-03,67.450578,118.127103,17.40,19.30,29.70,23.483476,17.40,29.07,30.70,6.80000,16.400000,2.250000,166.463581,NaN
3,Ahmedabad,2015-01-04,67.450578,118.127103,1.70,18.48,17.97,23.483476,1.70,18.59,36.08,4.43000,10.140000,1.000000,166.463581,NaN
4,Ahmedabad,2015-01-05,67.450578,118.127103,22.10,21.42,37.76,23.483476,22.10,39.33,39.31,7.01000,18.890000,2.780000,166.463581,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,2020-06-27,15.020000,50.940000,7.68,25.06,19.54,12.470000,0.47,8.55,23.30,2.24000,12.070000,0.730000,41.000000,Good
29527,Visakhapatnam,2020-06-28,24.380000,74.090000,3.42,26.06,16.53,11.990000,0.52,12.72,30.14,0.74000,2.210000,0.380000,70.000000,Satisfactory
29528,Visakhapatnam,2020-06-29,22.910000,65.730000,3.45,29.53,18.33,10.710000,0.48,8.42,30.96,0.01000,0.010000,0.000000,68.000000,Satisfactory
29529,Visakhapatnam,2020-06-30,16.640000,49.970000,4.05,29.26,18.80,10.030000,0.52,9.84,28.30,0.00000,0.000000,0.000000,54.000000,Satisfactory
29530,Visakhapatnam,2020-07-01,15.000000,66.000000,0.40,26.85,14.05,5.200000,0.59,2.10,17.05,3.28084,8.700972,3.070128,50.000000,Good

In [287]:
# dist = df2['City']
# distset = set(dist)
# dd = list(distset)
# dictofwords = {dd[i]: i for i in range(len(dd))}
# df2['City'] = df2['City'].map(dictofwords)

In [288]:
df2['City']

0            Ahmedabad
1            Ahmedabad
2            Ahmedabad
3            Ahmedabad
4            Ahmedabad
             ...
29526    Visakhapatnam
29527    Visakhapatnam
29528    Visakhapatnam
29529    Visakhapatnam
29530    Visakhapatnam
Name: City, Length: 29531, dtype: object

In [289]:
df2 = df2.drop('AQI_Bucket', axis=1)

In [290]:
df2 = df2.drop('Date', axis=1)

In [291]:
df2

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
0,Ahmedabad,67.450578,118.127103,0.92,18.22,17.15,23.483476,0.92,27.64,133.36,0.00000,0.020000,0.000000,166.463581
1,Ahmedabad,67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68000,5.500000,3.770000,166.463581
2,Ahmedabad,67.450578,118.127103,17.40,19.30,29.70,23.483476,17.40,29.07,30.70,6.80000,16.400000,2.250000,166.463581
3,Ahmedabad,67.450578,118.127103,1.70,18.48,17.97,23.483476,1.70,18.59,36.08,4.43000,10.140000,1.000000,166.463581
4,Ahmedabad,67.450578,118.127103,22.10,21.42,37.76,23.483476,22.10,39.33,39.31,7.01000,18.890000,2.780000,166.463581
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,15.020000,50.940000,7.68,25.06,19.54,12.470000,0.47,8.55,23.30,2.24000,12.070000,0.730000,41.000000
29527,Visakhapatnam,24.380000,74.090000,3.42,26.06,16.53,11.990000,0.52,12.72,30.14,0.74000,2.210000,0.380000,70.000000
29528,Visakhapatnam,22.910000,65.730000,3.45,29.53,18.33,10.710000,0.48,8.42,30.96,0.01000,0.010000,0.000000,68.000000
29529,Visakhapatnam,16.640000,49.970000,4.05,29.26,18.80,10.030000,0.52,9.84,28.30,0.00000,0.000000,0.000000,54.000000
29530,Visakhapatnam,15.000000,66.000000,0.40,26.85,14.05,5.200000,0.59,2.10,17.05,3.28084,8.700972,3.070128,50.000000

In [292]:
df2.isnull().sum()

City       0
PM2.5      0
PM10       0
NO         0
NO2        0
NOx        0
NH3        0
CO         0
SO2        0
O3         0
Benzene    0
Toluene    0
Xylene     0
AQI        0
dtype: int64

In [293]:
import plotly.express as px 

fig = px.scatter(df2, x="City", y="AQI")

fig.show()

In [294]:
fig = px.scatter(df2, x="PM10", y="AQI", color_discrete_sequence=['red'])

fig.show()

In [295]:
fig = px.scatter(df2, x="NOx", y="AQI", color_discrete_sequence=['green'])

fig.show()

In [296]:
fig = px.scatter(df2, x="NH3", y="AQI", color_discrete_sequence=['blue'])

fig.show()

In [297]:
fig = px.scatter(df2, x="CO", y="AQI", color_discrete_sequence=['black'])

fig.show()

In [298]:
fig = px.scatter(df2, x="SO2", y="AQI", color_discrete_sequence=['gray'])

fig.show()

In [299]:
fig = px.scatter(df2, x="Benzene", y="AQI", color_discrete_sequence=['yellow'])

fig.show()

In [300]:
fig = px.scatter(df2, x="Xylene", y="AQI", color_discrete_sequence=['darkturquoise'])

fig.show()

In [301]:
df2.columns

Index(['City', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3',
       'Benzene', 'Toluene', 'Xylene', 'AQI'],
      dtype='object')

In [302]:
features = df2[['City', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3',
       'Benzene', 'Toluene', 'Xylene']]

labels = df2['AQI']

In [303]:
features

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene
0,Ahmedabad,67.450578,118.127103,0.92,18.22,17.15,23.483476,0.92,27.64,133.36,0.00000,0.020000,0.000000
1,Ahmedabad,67.450578,118.127103,0.97,15.69,16.46,23.483476,0.97,24.55,34.06,3.68000,5.500000,3.770000
2,Ahmedabad,67.450578,118.127103,17.40,19.30,29.70,23.483476,17.40,29.07,30.70,6.80000,16.400000,2.250000
3,Ahmedabad,67.450578,118.127103,1.70,18.48,17.97,23.483476,1.70,18.59,36.08,4.43000,10.140000,1.000000
4,Ahmedabad,67.450578,118.127103,22.10,21.42,37.76,23.483476,22.10,39.33,39.31,7.01000,18.890000,2.780000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
29526,Visakhapatnam,15.020000,50.940000,7.68,25.06,19.54,12.470000,0.47,8.55,23.30,2.24000,12.070000,0.730000
29527,Visakhapatnam,24.380000,74.090000,3.42,26.06,16.53,11.990000,0.52,12.72,30.14,0.74000,2.210000,0.380000
29528,Visakhapatnam,22.910000,65.730000,3.45,29.53,18.33,10.710000,0.48,8.42,30.96,0.01000,0.010000,0.000000
29529,Visakhapatnam,16.640000,49.970000,4.05,29.26,18.80,10.030000,0.52,9.84,28.30,0.00000,0.000000,0.000000
29530,Visakhapatnam,15.000000,66.000000,0.40,26.85,14.05,5.200000,0.59,2.10,17.05,3.28084,8.700972,3.070128

In [304]:
labels

0        166.463581
1        166.463581
2        166.463581
3        166.463581
4        166.463581
            ...
29526     41.000000
29527     70.000000
29528     68.000000
29529     54.000000
29530     50.000000
Name: AQI, Length: 29531, dtype: float64

In [305]:
from sklearn.model_selection import train_test_split

In [306]:
Xtrain, Xtest, Ytrain, Ytest = train_test_split(features, labels, test_size=0.2, random_state=2)

In [307]:
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn import tree

In [308]:
Xtrain = pd.get_dummies(Xtrain)
Xtest = pd.get_dummies(Xtest)

# Align the test set columns with train
Xtest = Xtest.reindex(columns=Xtrain.columns, fill_value=0)

In [309]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression 
regr = RandomForestRegressor(max_depth=2, random_state=0)
regr.fit(Xtrain, Ytrain)
print(regr.predict(Xtest))

[120.44445696 120.44445696 120.44445696 ... 120.44445696 307.33721799
 307.33721799]

In [310]:
y_pred = regr.predict(Xtest)

In [311]:
from sklearn.metrics import r2_score
r2_score(Ytest, y_pred)

0.6540144120689928

In [ ]:

def predict_aqi():
  
    city = input("Enter City: ")
    pm25 = float(input("Enter PM2.5 value: "))
    pm10 = float(input("Enter PM10 value: "))
    no = float(input("Enter NO value: "))
    no2 = float(input("Enter NO2 value: "))
    nox = float(input("Enter NOx value: "))
    nh3 = float(input("Enter NH3 value: "))
    co = float(input("Enter CO value: "))
    so2 = float(input("Enter SO2 value: "))
    o3 = float(input("Enter O3 value: "))
    benzene = float(input("Enter Benzene value: "))
    toluene = float(input("Enter Toluene value: "))
    xylene = float(input("Enter Xylene value: "))

   
    input_data = pd.DataFrame({
        'City': [city],
        'PM2.5': [pm25],
        'PM10': [pm10],
        'NO': [no],
        'NO2': [no2],
        'NOx': [nox],
        'NH3': [nh3],
        'CO': [co],
        'SO2': [so2],
        'O3': [o3],
        'Benzene': [benzene],
        'Toluene': [toluene],
        'Xylene': [xylene]
    })

   
    input_data = pd.get_dummies(input_data)
    input_data = input_data.reindex(columns=Xtrain.columns, fill_value=0)

    
    prediction = regr.predict(input_data)
    print(f"Predicted AQI: {prediction[0]}")

predict_aqi()

Predicted AQI: 447.54210176311005